owner: xtexChooser
repo: upptime
user-agent: xtexChooser(Upptime)/1.0

sites:
  - name: Home
    url: https://xtexx.ml/
  - name: Blog
    url: https://blog.xtexx.ml/
  - name: Upptime
    url: https://status.xtexx.ml/
  - name: nl-alk1
    check: "tcp-ping"
    url: nl-alk1.svr.xvnet.eu.org
    port: 22
  - name: us-lax1
    check: "tcp-ping"
    url: us-lax1.svr.xvnet.eu.org
    port: 22

status-website:
  cname: status.xtexx.ml
  logoUrl: https://blog.xtexx.ml/icon.png
  favicon: https://blog.xtexx.ml/icon.png
  name: xtex's Upptime
  introTitle: xtex's Upptime
  introMessage: "Service availablity information for services maintainced by @xtexChooser."
  theme: night
  apiBaseUrl: https://rp.chitang.dev/https://api.github.com
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://xtexx.ml/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - xtexChooser
