owner: xtexChooser
repo: upptime
user-agent: xtexChooser(Upptime)/1.0

sites:
  - name: Blog
    url: https://xtexx.ml/blog/
  - name: Upptime
    url: https://upptime.xtexx.ml/
  - name: Server cn-gz1
    check: "tcp-ping"
    url: cn-gz1.svr.xtexx.ml
    port: 22

status-website:
  cname: upptime.xtexx.ml
  logoUrl: https://xtexx.ml/blog/icon.png
  favicon: https://xtexx.ml/blog/icon.png
  name: xtex's Upptime
  introTitle: xtex's Upptime
  introMessage: "Service availablity information for services maintainced by @xtexChooser."
  theme: dark
  apiBaseUrl: https://rp.chitang.dev/https://api.github.com
  navbar:
    - title: Status
      href: /
    - title: Blog
      href: https://xtexx.ml/blog/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - xtexChooser
