owner: xtexChooser
repo: upptime
user-agent: xtexChooser

sites:
  - name: Blog
    url: https://xtexx.ml/blog/
  - name: Server cn-gz1
    check: "tcp-ping"
    url: cn-gz1.svr.xtexx.ml
    port: 22

status-website:
  cname: upptime.xtexx.ml
  logoUrl: https://xtexx.ml/blog/icon.png
  name: xtex's Upptime
  introTitle: "Service status monitoring by xtex"
  introMessage: "This shows service availablity information for services maintainced by @xtexChooser."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - xtexChooser
